import { Player, MatchState } from '../types';

export const DEFAULT_PLAYERS: Player[] = [
  {
    id: '1',
    name: 'Jorge Souto',
    number: 10,
    position: 'Especialista',
    isActiveOnCourt: true,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: true,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '2',
    name: 'Carlos Sanz',
    number: 7,
    position: 'Ala Izq.',
    isActiveOnCourt: true,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: true,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '3',
    name: 'Mateo Almeida',
    number: 1,
    position: 'Portero',
    isActiveOnCourt: true,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: true,
    predefinedDefense: true,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '4',
    name: 'Dani Blanco',
    number: 99,
    position: 'Ala Der.',
    isActiveOnCourt: true,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: true,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '5',
    name: 'Alex García',
    number: 5,
    position: 'Pivote',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: true,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '6',
    name: 'Hugo Castro',
    number: 22,
    position: 'Defensor',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: true,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '7',
    name: 'Adrián Ortiz',
    number: 13,
    position: 'Defensor',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: true,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '8',
    name: 'Santi Moreno',
    number: 8,
    position: 'Especialista',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '9',
    name: 'Lucas Gil',
    number: 12,
    position: 'Portero',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
  {
    id: '10',
    name: 'David Ramos',
    number: 17,
    position: 'Pivote',
    isActiveOnCourt: false,
    exclusions: 0,
    isDisqualified: false,
    predefinedAttack: false,
    predefinedDefense: false,
    goals1p: 0,
    goals2p: 0, goalsFlies: 0, goalsSpins: 0, goalsPenalties: 0, assists: 0, missedShots: 0,
    missedFlies: 0, missedSpins: 0, missedPenalties: 0,
    turnoverBadPass: 0,
    turnoverSteps: 0,
    turnoverFumbling: 0,
    recoveries: 0,
  },
];

export const SHIRT_COLORS = [
  { name: 'Rojo', hex: '#ef4444', text: 'text-white', bg: 'bg-red-550', border: 'border-red-600' },
  { name: 'Azul', hex: '#3b82f6', text: 'text-white', bg: 'bg-blue-550', border: 'border-blue-600' },
  { name: 'Amarillo', hex: '#eab308', text: 'text-black', bg: 'bg-yellow-400', border: 'border-yellow-500' },
  { name: 'Verde', hex: '#22c55e', text: 'text-white', bg: 'bg-green-550', border: 'border-green-600' },
  { name: 'Naranja', hex: '#f97316', text: 'text-white', bg: 'bg-orange-550', border: 'border-orange-600' },
  { name: 'Blanco', hex: '#ffffff', text: 'text-black', bg: 'bg-gray-150', border: 'border-gray-300' },
  { name: 'Negro', hex: '#000000', text: 'text-white', bg: 'bg-black', border: 'border-zinc-800' },
];

export const INITIAL_SET_STATE = (setNumber: 1 | 2): any => ({
  setNumber,
  usScore: 0,
  themScore: 0,
  usTTOUsed: false,
  themTTOUsed: false,
  ttoActive: false,
  ttoSecondsLeft: 60,
  isGoldenGoal: false,
  isFinished: false,
  winner: null,
});

export const INITIAL_MATCH_STATE: MatchState = {
  currentPeriod: 'set1',
  set1: INITIAL_SET_STATE(1),
  set2: INITIAL_SET_STATE(2),
  shootoutRounds: Array.from({ length: 5 }, () => ({ usGoal: null, themGoal: null })),
  activePossession: 'us',
  passivePasses: null,
  players: DEFAULT_PLAYERS,
  opponentName: 'Oponente',
  ourTeamName: 'Mi Equipo',
  rulesAlertActive: false,
};



